const fs = require('fs');
let content = fs.readFileSync('src/lib/i18n.ts', 'utf8');

content = content.replace(
  "'profile.theme_desc': 'Switch between light and dark themes',",
  "'profile.theme_desc': 'Switch between light and dark themes',\n    'profile.status': 'Status',\n    'profile.business': 'Business',\n    'profile.trust_rating': 'Trust Rating',\n    'profile.role': 'Role',\n    'profile.family_demographics': 'Family & Demographics',\n    'profile.nationality': 'Nationality',\n    'profile.num_children': 'Number of Children',\n    'profile.ages_example': 'Ages (e.g. 5, 8)',\n    'profile.notif_prefs': 'Notification Preferences',\n    'profile.security_alerts': 'Security & Alerts',\n    'profile.security_alerts_desc': 'Emergency alerts, suspicious activities, neighborhood watch updates',\n    'profile.direct_msgs': 'Direct Messages',\n    'profile.direct_msgs_desc': 'When neighbors message you or reply to your comments',\n    'profile.market_activity': 'Marketplace Activity',\n    'profile.market_activity_desc': 'New items given away or lent nearby, offers on your listings',\n    'profile.comm_events': 'Community Events',\n    'profile.comm_events_desc': 'Local meetups, building meetings, neighborhood gatherings',\n    'profile.accessibility': 'Accessibility',"
);

content = content.replace(
  "'profile.theme_desc': 'İşıqlı və qaranlıq rejimlər arasında keçid edin',",
  "'profile.theme_desc': 'İşıqlı və qaranlıq rejimlər arasında keçid edin',\n    'profile.status': 'Status',\n    'profile.business': 'Biznes',\n    'profile.trust_rating': 'Etibar Reytinqi',\n    'profile.role': 'Rol',\n    'profile.family_demographics': 'Ailə və Demoqrafiya',\n    'profile.nationality': 'Milliyyət',\n    'profile.num_children': 'Uşaqların Sayı',\n    'profile.ages_example': 'Yaşları (məs. 5, 8)',\n    'profile.notif_prefs': 'Bildiriş Tənzimləmələri',\n    'profile.security_alerts': 'Təhlükəsizlik və Xəbərdarlıqlar',\n    'profile.security_alerts_desc': 'Fövqəladə xəbərdarlıqlar, şübhəli fəaliyyətlər, məhəllə yenilikləri',\n    'profile.direct_msgs': 'Birbaşa Mesajlar',\n    'profile.direct_msgs_desc': 'Qonşular sizə mesaj yazdıqda və ya rəylərinizə cavab verdikdə',\n    'profile.market_activity': 'Bazar Aktivliyi',\n    'profile.market_activity_desc': 'Yaxınlıqda verilən və ya borc verilən yeni əşyalar, elanlarınıza təkliflər',\n    'profile.comm_events': 'İcma Tədbirləri',\n    'profile.comm_events_desc': 'Yerli görüşlər, bina iclasları, məhəllə toplanışları',\n    'profile.accessibility': 'Əlçatanlıq',"
);

content = content.replace(
  "'profile.theme_desc': 'Переключение между светлой и темной темой',",
  "'profile.theme_desc': 'Переключение между светлой и темной темой',\n    'profile.status': 'Статус',\n    'profile.business': 'Бизнес',\n    'profile.trust_rating': 'Рейтинг Доверия',\n    'profile.role': 'Роль',\n    'profile.family_demographics': 'Семья и Демография',\n    'profile.nationality': 'Национальность',\n    'profile.num_children': 'Количество Детей',\n    'profile.ages_example': 'Возраст (напр. 5, 8)',\n    'profile.notif_prefs': 'Настройки Уведомлений',\n    'profile.security_alerts': 'Безопасность и Предупреждения',\n    'profile.security_alerts_desc': 'Экстренные предупреждения, подозрительные действия, новости района',\n    'profile.direct_msgs': 'Личные Сообщения',\n    'profile.direct_msgs_desc': 'Когда соседи пишут вам или отвечают на комментарии',\n    'profile.market_activity': 'Активность на Маркете',\n    'profile.market_activity_desc': 'Новые вещи, отданные или одолженные поблизости, предложения по вашим объявлениям',\n    'profile.comm_events': 'События Сообщества',\n    'profile.comm_events_desc': 'Местные встречи, собрания дома, собрания района',\n    'profile.accessibility': 'Доступность',"
);

fs.writeFileSync('src/lib/i18n.ts', content);
