cat src/components/Marketplace.tsx | awk '
BEGIN { output=1; }
/import \{ Tag,/ { print "import { Tag, MapPin, Plus, X, HandHeart, RefreshCw, Flag, Eye, ThumbsUp } from '\''lucide-react'\'';"; output=0; next }
/import \{ useModerationStore \}/ { print; output=1; next }
/const \[items, setItems\] = useState\(\[/ { print "  const [items, setItems] = useState([\n    { id: 1, title: '\''IKEA Office Chair'\'', type: '\''sell'\'', price: '\''45 ₼'\'', category: '\''Furniture'\'', image: '\''https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=400&h=300&fit=crop'\'', distance: '\''100m'\'', distanceNum: 100, views: 12, helpful: 3 },\n    { id: 2, title: '\''Bicycle (Adult)'\'', type: '\''sell'\'', price: '\''120 ₼'\'', category: '\''Sports'\'', image: '\''https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=300&fit=crop'\'', distance: '\''300m'\'', distanceNum: 300, views: 45, helpful: 8 },\n    { id: 3, title: '\''Moving Boxes'\'', type: '\''giveaway'\'', price: '\''Free'\'', category: '\''Other'\'', image: '\''https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=400&h=300&fit=crop'\'', distance: '\''50m'\'', distanceNum: 50, views: 8, helpful: 1 },\n    { id: 4, title: '\''Power Drill'\'', type: '\''lend'\'', price: '\''Lend'\'', category: '\''Tools'\'', image: '\''https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=300&fit=crop'\'', distance: '\''400m'\'', distanceNum: 400, views: 32, helpful: 5 },\n  ]);\n  const [filter, setFilter] = useState('\''closest'\'');"; output=0; next }
/const \[showForm/ { print; output=1; next }
/setItems\(\[/ { print "    setItems([\n      {\n        id: items.length + 1,\n        title: newItem.title,\n        type: newItem.type,\n        price: newItem.price || '\''Free'\'',\n        category: newItem.category,\n        image: '\''https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&h=300&fit=crop'\'',\n        distance: '\''0m'\'',\n        distanceNum: 0,\n        views: 0,\n        helpful: 0\n      },\n      ...items\n    ]);"; output=0; next }
/setShowForm\(false\);/ { print; output=1; next }
/return \(/ { print "  const handleItemClick = (id: number) => {\n    setItems(items.map(item => item.id === id ? { ...item, views: item.views + 1 } : item));\n  };\n\n  const handleHelpfulClick = (e: React.MouseEvent, id: number) => {\n    e.stopPropagation();\n    setItems(items.map(item => item.id === id ? { ...item, helpful: item.helpful + 1 } : item));\n  };\n\n  const sortedItems = [...items].sort((a, b) => {\n    if (filter === '\''closest'\'') return a.distanceNum - b.distanceNum;\n    if (filter === '\''helpful'\'') return b.helpful - a.helpful;\n    if (filter === '\''category'\'') return a.category.localeCompare(b.category);\n    if (filter === '\''alphabetical'\'') return a.title.localeCompare(b.title);\n    return 0;\n  });\n\n  return ("; output=0; next }
/<div className=\"flex items-center justify-between\">/ { print "      <div className=\"flex items-center justify-between\">\n        <div>\n          <h2 className=\"text-2xl font-bold tracking-tight text-slate-900 dark:text-white\">{t('\''market.title'\'', language)}</h2>\n          <p className=\"text-slate-600 dark:text-slate-400 text-sm mt-1\">{t('\''market.subtitle'\'', language)}</p>\n        </div>\n        <select \n          className=\"bg-white/50 dark:bg-black/50 border border-black/10 dark:border-white/10 rounded-md text-sm px-2 py-1 text-slate-700 dark:text-slate-300 outline-none focus:ring-2 focus:ring-blue-500\"\n          value={filter}\n          onChange={(e) => setFilter(e.target.value)}\n        >\n          <option value=\"closest\">Closest to furthest</option>\n          <option value=\"helpful\">Most helpful first</option>\n          <option value=\"category\">By category</option>\n          <option value=\"alphabetical\">Alphabetically</option>\n        </select>\n      </div>"; output=0; next }
/<VerificationGate>/ { print; output=1; next }
/\{items\.map\(item => \(/ { print "        {sortedItems.map(item => (\n          <Card key={item.id} onClick={() => handleItemClick(item.id)} className=\"glass-panel overflow-hidden group cursor-pointer border-black/10 dark:border-white/10 hover:shadow-xl transition-all relative\">"; output=0; next }
/<div className=\"absolute top-2 right-2 z-10 flex space-x-1\">/ { print; output=1; next }
/ <div className=\"flex items-center text-xs text-slate-600 dark:text-slate-400 font-medium\">/ { print "                <div className=\"flex items-center justify-between text-xs text-slate-600 dark:text-slate-400 font-medium\">\n                  <div className=\"flex items-center\">\n                    {item.type === '\''lend'\'' ? <RefreshCw className=\"h-3 w-3 mr-1 text-blue-400\" /> :\n                     item.type === '\''giveaway'\'' ? <HandHeart className=\"h-3 w-3 mr-1 text-green-400\" /> :\n                     <Tag className=\"h-3 w-3 mr-1 text-orange-400\" />}\n                    <span className=\"capitalize\">{item.type}</span>\n                  </div>\n                  <div className=\"flex items-center space-x-2 text-slate-500\">\n                    <span className=\"flex items-center\"><Eye className=\"h-3 w-3 mr-1\"/> {item.views}</span>\n                    <button onClick={(e) => handleHelpfulClick(e, item.id)} className=\"flex items-center hover:text-blue-500 transition-colors\">\n                      <ThumbsUp className=\"h-3 w-3 mr-1\"/> {item.helpful}\n                    </button>\n                  </div>\n                </div>"; output=0; next }
/ <div className=\"flex items-center text-xs text-slate-500 dark:text-slate-500 font-medium\">/ { print; output=1; next }
{ if (output) print }
' > src/components/Marketplace_new.tsx
mv src/components/Marketplace_new.tsx src/components/Marketplace.tsx
